$(document).ready(function(){
	//焦点在账号密码输入框之间切换时根据用户是否输入数据在输入框下方提示
		$("#user").focus(function(){
			$("#remind_1").text("");
			$("#change_margin_1").css("marginBottom","19px");
		});
		$("#password").focus(function(){
			$("#remind_2").text("");
			$("#change_margin_2").css("marginBottom","19px");
			$("#change_margin_3").css("marginTop","19px");
		});
		$("#user").blur(function(){
			if($("#user").val()==""){
				$("#remind_1").text("请输入用户名！");
				$("#change_margin_1").css("marginBottom","1px");
			}else{
				$("#remind_1").text("");
				$("#change_margin_1").css("marginBottom","19px");
			}
		});
		$("#password").blur(function(){
			if($("#password").val()==""){
				$("#remind_2").text("请输入密码！");
				$("#change_margin_2").css("marginBottom","1px");
				$("#change_margin_3").css("marginTop","2px");
			}else{
				$("#remind_2").text("");
				$("#change_margin_2").css("marginBottom","19px");
				$("#change_margin_3").css("marginTop","19px");
			}
		});
	//点击登录按钮之后的处理
		$("form").submit(function(e){
			if($("#user").val()!=""&&$("#password").val()!=""){
				if($("#user").val()!="admin"||$("#password").val()!="admin"){
					e.preventDefault();
					alert("账号密码输入有误，请重新确认！");
				}
			}else{
				e.preventDefault();
				if($("#user").val()==""){
					$("#remind_1").text("请输入用户名！");
					$("#change_margin_1").css("marginBottom","1px");
				}
				if($("#password").val()==""){
					$("#remind_2").text("请输入密码！");
					$("#change_margin_2").css("marginBottom","1px");
					$("#change_margin_3").css("marginTop","2px");
				}
			}
		});
	});
	
